#!/usr/bin/env python3
"""Convert the official NIP-44 v2 vector suite to tests/nip44-vectors.tcl.

Usage:  python3 tests/vectors2tcl.py /path/to/nip44.vectors.json > tests/nip44-vectors.tcl

Source: https://raw.githubusercontent.com/paulmillr/nip44/main/nip44.vectors.json
Free-text fields (plaintexts, patterns, notes) are hex-encoded UTF-8 so
no Tcl quoting can bite; the test suite decodes them back.
"""

import hashlib
import json
import sys


def hx(s):
    return s.encode("utf-8").hex()


def main():
    path = sys.argv[1]
    raw = open(path, "rb").read()
    v2 = json.loads(raw)["v2"]
    out = sys.stdout

    out.write("# Generated by vectors2tcl.py from the official NIP-44 v2\n")
    out.write("# vector suite -- do not edit.\n")
    out.write("#   source: https://raw.githubusercontent.com/paulmillr/"
              "nip44/main/nip44.vectors.json\n")
    out.write("#   sha256: %s\n" % hashlib.sha256(raw).hexdigest())
    out.write("# get_message_keys vectors are omitted: the derived keys are\n")
    out.write("# internal to the C core and fully exercised by the\n")
    out.write("# encrypt/decrypt vectors.\n\n")

    out.write("set NIP44_CONVKEY_VALID {\n")
    for e in v2["valid"]["get_conversation_key"]:
        out.write("    {%s %s %s}\n"
                  % (e["sec1"], e["pub2"], e["conversation_key"]))
    out.write("}\n\n")

    out.write("set NIP44_PADDED {\n")
    for pair in v2["valid"]["calc_padded_len"]:
        out.write("    {%d %d}\n" % (pair[0], pair[1]))
    out.write("}\n\n")

    out.write("set NIP44_ENCDEC {\n")
    for e in v2["valid"]["encrypt_decrypt"]:
        out.write("    {%s %s %s %s %s %s}\n"
                  % (e["sec1"], e["sec2"], e["conversation_key"], e["nonce"],
                     hx(e["plaintext"]), e["payload"]))
    out.write("}\n\n")

    out.write("set NIP44_LONG {\n")
    for e in v2["valid"]["encrypt_decrypt_long_msg"]:
        out.write("    {%s %s %s %d %s %s}\n"
                  % (e["conversation_key"], e["nonce"], hx(e["pattern"]),
                     e["repeat"], e["plaintext_sha256"], e["payload_sha256"]))
    out.write("}\n\n")

    out.write("set NIP44_INVALID_LEN {%s}\n\n"
              % " ".join(str(n) for n in v2["invalid"]["encrypt_msg_lengths"]))

    out.write("set NIP44_INVALID_CONVKEY {\n")
    for e in v2["invalid"]["get_conversation_key"]:
        out.write("    {%s %s %s}\n" % (e["sec1"], e["pub2"], hx(e["note"])))
    out.write("}\n\n")

    out.write("set NIP44_INVALID_DECRYPT {\n")
    for e in v2["invalid"]["decrypt"]:
        out.write("    {%s %s %s}\n"
                  % (e["conversation_key"], e["payload"], hx(e["note"])))
    out.write("}\n")


if __name__ == "__main__":
    main()
